#ifndef _JIA_XCONTROLS_
#define _JIA_XCONTROLS_

#include "XButton.h"
#include "XButtonEx.h"
#include "XSlider.h"
#include "XProgress.h"
#include "XCheck.h"
#include "XRadios.h"
#include "XMouseRightButtonMenu.h"
#include "XEdit.h"
#include "XMultiText.h"
#include "XMultiEdit.h"
#include "XMultiList.h"
#include "XMultiListBasic.h"
#include "XCombo.h"
#include "XPasswordPad.h"
#include "XDirectoryList.h"
#include "XGroup.h"
#include "XPointCtrl.h"
#include "XLineCtrl.h"
#include "XSliderEx.h"
#include "XImageList.h"
#include "XChart.h"
#include "XTab.h"
#include "XSubWindow.h"
#include "XProgressRing.h"
#include "XSimpleLine.h"
#include "XText.h"
#include "XCalendar.h"
#include "XMenu.h"

#include "XImageCtrl.h"
#include "XComment.h"
#include "XButtonBar.h"
#include "XToolBar.h"
#include "XPropertyBox.h"
#include "XColorChoose.h"

#include "XTimeLine.h"

#endif
